#!/bin/bash

# 下载 Anaconda 安装器
wget https://repo.anaconda.com/archive/Anaconda3-2025.12-1-Linux-x86_64.sh

# 给安装脚本赋予执行权限
chmod +x ./Anaconda3-2025.12-1-Linux-x86_64.sh

# 运行安装脚本
bash ./Anaconda3-2025.12-1-Linux-x86_64.sh -b

source /root/anaconda3/bin/activate
sudo bash -c 'echo -e "source /root/anaconda3/bin/activate" >> ~/.bashrc'
 

